# ヘルプメッセージ
help:
	@echo "🚀 Ubuntu開発環境セットアップ"
	@echo ""
	@echo "📋 利用可能なコマンド（新しい階層的な命名規則）:"
	@echo ""
	@echo "🔧 システム設定:"
	@echo "  make setup-system                     - システムレベルの基本設定"
	@echo ""
	@echo "📦 パッケージ・ソフトウェアのインストール:"
	@echo "  make install-packages-homebrew        - Homebrewをインストール"
	@echo "  make install-packages-apps            - Brewfileを使用してアプリケーションをインストール"
	@echo "  make install-packages-deb             - DEBパッケージをインストール（IDE・ブラウザ含む）"
	@echo "  make install-packages-flatpak         - Flatpakパッケージをインストール"
	@echo "  make install-packages-fuse            - AppImage実行用のFUSEパッケージをインストール"
	@echo "  make install-packages-wezterm         - WezTerm（AppImage版）をインストール"
	@echo "  make install-packages-cursor          - Cursor IDEをインストール"
	@echo "  make install-packages-claude-code     - Claude Code（AI コードエディタ）をインストール"
	@echo "  make install-packages-claudia         - Claudia（Claude Code GUI）をインストール"
	@echo "  make install-packages-superclaude     - SuperClaude（Claude Code フレームワーク）をインストール"
	@echo "  make install-packages-claude-ecosystem - Claude Code エコシステム一括インストール"
	@echo "  make install-claude-ecosystem         - Claude Code エコシステム一括インストール（直接ターゲット）"
	@echo "  make install-packages-cica-fonts      - Cica Nerd Fontsをインストール"
	@echo "  make install-packages-mysql-workbench - MySQL Workbenchをインストール"
	@echo "  make install-packages-chrome-beta     - Google Chrome Betaをインストール"
	@echo "  make install-packages-playwright      - Playwright E2Eテストフレームワークをインストール"
	@echo ""
	@echo "⚙️  設定ファイル・コンフィグのセットアップ:"
	@echo "  make setup-config-vim                 - VIMの設定をセットアップ"
	@echo "  make setup-config-zsh                 - ZSHの設定をセットアップ"
	@echo "  make setup-config-wezterm             - WEZTERMの設定をセットアップ"
	@echo "  make setup-config-vscode              - VS Codeの設定をセットアップ"
	@echo "  make setup-config-vscode-copilot      - VS Code用のSuperCopilotフレームワークをセットアップ"
	@echo "  make setup-config-cursor              - Cursorの設定をセットアップ"
	@echo "  make setup-config-mcp-tools           - Cursor MCP Toolsの設定をセットアップ"
	@echo "  make setup-config-git                 - Git設定をセットアップ"
	@echo "  make setup-config-docker              - Dockerの設定をセットアップ"
	@echo "  make setup-config-development         - 開発環境の設定をセットアップ"
	@echo "  make setup-config-shortcuts           - キーボードショートカットの設定をセットアップ"
	@echo "  make setup-config-ime                 - 日本語入力（IME）環境をセットアップ"
	@echo "  make setup-config-claude              - Claude設定をセットアップ"
	@echo "  make setup-config-lazygit             - Lazygitの設定をセットアップ"
	@echo "  make setup-config-gnome-extensions    - Gnome Extensions の設定をセットアップ"
	@echo "  make setup-config-gnome-tweaks        - Gnome Tweaks の設定をセットアップ"
	@echo "  make setup-config-mozc                - Mozc入力メソッドの設定をセットアップ"
	@echo "  make setup-config-mozc-ut-dictionaries - Mozc UT辞書の設定を開始"
	@echo "  make setup-config-mozc-ut-dictionaries-manual - Mozc UT辞書の手動インポート手順を表示"
	@echo "  make setup-claude                     - Claude Code設定ファイルのセットアップ"
	@echo "  make setup-config-all                 - すべての設定をセットアップ"
	@echo ""
	@echo "🔧 管理・バックアップ:"
	@echo "  make backup-config-gnome-tweaks       - Gnome Tweaks の設定をバックアップ"
	@echo "  make export-config-gnome-tweaks       - Gnome Tweaks の設定をエクスポート"
	@echo "  make fix-extensions-schema            - Gnome Extensions スキーマエラーを修復"
	@echo "  make update-cursor                    - Cursor IDEを最新版にアップデート"
	@echo "  make stop-cursor                      - 実行中のCursor IDEを停止"
	@echo "  make check-cursor-version             - Cursor IDEのバージョン情報を確認"
	@echo "  make clean                            - シンボリックリンクを削除"
	@echo "  make clean-repos                      - リポジトリとGPGキーをクリーンアップ"
	@echo "  make help                             - このヘルプメッセージを表示"
	@echo ""
	@echo "📋 後方互換性のために古い名前も引き続き使用可能です (例: make install-homebrew)"
	@echo ""
	@echo "📦 推奨実行順序（新しい命名規則）:"
	@echo "  1. make setup-system"
	@echo "  2. make install-packages-homebrew"
	@echo "  3. make install-packages-deb       (IDE・ブラウザ・WezTerm含む)"
	@echo "  4. make install-claude-ecosystem   (Claude Code関連ツール一括)"
	@echo "  5. make setup-config-all"
	@echo ""
	@echo "🌟 一括セットアップ:"
	@echo "  make setup-config-all                  - 上記1-5を自動実行（推奨）"
	@echo "  ※ Claude Codeエコシステムも自動的にインストールされます"
	@echo ""
	@echo "🌏 日本語環境について:"
	@echo "  'make setup-system' で日本語フォント・ロケール・mozc（日本語入力）がインストールされます"
	@echo ""
	@echo "🔤 フォントについて:"
	@echo "  'make setup-system' でIBM Plex Sans、日本語フォント（Noto CJK）がインストールされます"
	@echo "  'make install-packages-cica-fonts' でCica Nerd Fonts（プログラミング用）がインストールされます"
	@echo ""
	@echo "🌐 ブラウザについて:"
	@echo "  'make install-packages-deb' でGoogle Chrome Stable、Google Chrome Beta、Chromiumがインストールされます"
	@echo ""
	@echo "👨‍💻 開発環境IDEについて:"
	@echo "  'make install-packages-deb' で以下のIDEがインストールされます:"
	@echo "    - Visual Studio Code (公式リポジトリから)"
	@echo "    - Cursor IDE (AppImageとして /opt/cursor にインストール)"
	@echo "    - WezTerm (AppImageとして /opt/wezterm にインストール)"
	@echo "  'make install-packages-cursor' でCursor IDEをインストール"
	@echo "  'make update-cursor' でCursor IDEを最新版にアップデート"
	@echo "  'make check-cursor-version' でCursor IDEのバージョン情報を確認"
	@echo "  'make install-packages-claude-code' でClaude Code（AI コードエディタ）をインストール"
	@echo "  'make install-packages-claudia' でClaudia（Claude Code GUI）をインストール"
	@echo "  'make install-packages-superclaude' でSuperClaude（Claude Code フレームワーク）をインストール"
	@echo "  'make install-packages-claude-ecosystem' でClaude Code エコシステム一括インストール"
	@echo "  'make install-packages-wezterm' でWezTerm（AppImage版）をインストール"
	@echo ""
	@echo "📧 Eメールアドレスの設定:"
	@echo "  環境変数で指定: EMAIL=your@email.com make setup-config-git"
	@echo "  または実行時に入力プロンプトで設定可能"
	@echo ""
	@echo "💡 使用例:"
	@echo "  EMAIL=user@example.com make setup-config-all           # Eメール指定で全設定"
	@echo "  make setup-config-git                                  # 実行時にEメール入力"
	@echo "  make install-packages-claude-ecosystem                 # Claude Code関連ツール一括"
	@echo ""
	@echo "🤖 AI開発ツールについて:"
	@echo "  'make install-packages-claude-code' でClaude Code（CLI）をインストール"
	@echo "  'make install-packages-claudia' でClaudia（Claude CodeのGUIアプリ）をインストール"
	@echo "  'make install-packages-superclaude' でSuperClaude（Claude Code フレームワーク）をインストール"
	@echo "  'make install-packages-claude-ecosystem' で上記3つを一括インストール（推奨）"
	@echo ""
	@echo "  Claudiaは以下の機能を提供:"
	@echo "    - プロジェクト & セッション管理"
	@echo "    - カスタムAIエージェント作成"
	@echo "    - 使用状況分析ダッシュボード"
	@echo "    - MCP サーバー管理"
	@echo "    - タイムライン & チェックポイント機能"
	@echo ""
	@echo "  SuperClaude v3は以下の機能を提供:"
	@echo "    - 16の専門コマンド (/sc:implement, /sc:build, /sc:design等)"
	@echo "    - スマートペルソナ (architect, frontend, backend等)"
	@echo "    - MCPサーバー統合 (Context7, Sequential, Magic)"
	@echo "    - 100%ローカル実行"
	@echo ""
	@echo "📝 フォント管理:"
	@echo "  fonts-setup     - 全フォント環境のセットアップ"
	@echo "  fonts-install   - 全種類のフォントをインストール"
	@echo "  fonts-list      - インストール済みフォント一覧"
	@echo "  fonts-clean     - 一時ファイルのクリーンアップ"
	@echo "  fonts-update    - フォントの最新版への更新"
	@echo ""
	@echo "🆕 Ubuntu 25.04 (Plucky Puffin) 対応:"
	@echo "  新しいパッケージ名に対応しています（libfuse2t64など）"
	@echo "  一部のPPAが利用できない場合があります"
