# ヘルプメッセージ
help:
	@echo "🚀 Ubuntu開発環境セットアップ"
	@echo ""
	@echo "📋 利用可能なコマンド:"
	@echo "  make system-setup      - システムレベルの基本設定"
	@echo "  make install-homebrew  - Homebrewをインストール"
	@echo "  make install-apps      - Brewfileを使用してアプリケーションをインストール"
	@echo "  make install-deb       - DEBパッケージをインストール（IDE・ブラウザ含む）"
	@echo "  make install-flatpak   - Flatpakパッケージをインストール"
	@echo "  make setup-vim         - VIMの設定をセットアップ"
	@echo "  make setup-zsh         - ZSHの設定をセットアップ"
	@echo "  make setup-wezterm     - WEZTERMの設定をセットアップ"
	@echo "  make setup-vscode      - VS Codeの設定をセットアップ"
	@echo "  make setup-cursor      - Cursorの設定をセットアップ"
	@echo "  make setup-git         - Git設定をセットアップ"
	@echo "  make setup-docker      - Dockerの設定をセットアップ"
	@echo "  make setup-development     - 開発環境の設定をセットアップ"
	@echo "  make setup-shortcuts       - キーボードショートカットの設定をセットアップ"
	@echo "  make setup-gnome-extensions- Gnome Extensions の設定をセットアップ"
	@echo "  make fix-extensions-schema - Gnome Extensions スキーマエラーを修復"
	@echo "  make setup-gnome-tweaks    - Gnome Tweaks の設定をセットアップ"
	@echo "  make backup-gnome-tweaks   - Gnome Tweaks の設定をバックアップ"
	@echo "  make export-gnome-tweaks   - Gnome Tweaks の設定をエクスポート"
	@echo "  make setup-mozc            - Mozc入力メソッドの設定をセットアップ"
	@echo "  make setup-mozc-ut-dictionaries - Mozc UT辞書の設定を開始"
	@echo "  make setup-mozc-ut-dictionaries-manual - Mozc UT辞書の手動インポート手順を表示"
	@echo "  make setup-all             - すべての設定をセットアップ"
	@echo "  make install-fuse      - AppImage実行用のFUSEパッケージをインストール"
	@echo "  make install-wezterm   - WezTerm（AppImage版）をインストール"
	@echo "  make install-cica-fonts - Cica Nerd Fontsをインストール"
	@echo "  make install-mysql-workbench - MySQL Workbenchをインストール"
	@echo "  make clean             - シンボリックリンクを削除"
	@echo "  make clean-repos       - リポジトリとGPGキーをクリーンアップ"
	@echo "  make help              - このヘルプメッセージを表示"
	@echo ""
	@echo "📦 推奨実行順序:"
	@echo "  1. make system-setup"
	@echo "  2. make install-homebrew"
	@echo "  3. make install-deb       (IDE・ブラウザ・WezTerm含む)"
	@echo "  4. make setup-all"
	@echo ""
	@echo "🌏 日本語環境について:"
	@echo "  'make system-setup' で日本語フォント・ロケール・mozc（日本語入力）がインストールされます"
	@echo ""
	@echo "🔤 フォントについて:"
	@echo "  'make system-setup' でIBM Plex Sans、日本語フォント（Noto CJK）がインストールされます"
	@echo "  'make install-cica-fonts' でCica Nerd Fonts（プログラミング用）がインストールされます"
	@echo ""
	@echo "🌐 ブラウザについて:"
	@echo "  'make install-deb' でGoogle Chrome Stable/Beta、Chromiumがインストールされます"
	@echo ""
	@echo "👨‍💻 開発環境IDEについて:"
	@echo "  'make install-deb' で以下のIDEがインストールされます:"
	@echo "    - Visual Studio Code (公式リポジトリから)"
	@echo "    - Cursor IDE (AppImageとして /opt/cursor にインストール)"
	@echo "    - WezTerm (AppImageとして /opt/wezterm にインストール)"
	@echo "  'make install-cursor' でCursor IDEをインストール"
	@echo "  'make install-wezterm' でWezTerm（AppImage版）をインストール"
	@echo ""
	@echo "📧 Eメールアドレスの設定:"
	@echo "  環境変数で指定: EMAIL=your@email.com make setup-git"
	@echo "  または実行時に入力プロンプトで設定可能"
	@echo ""
	@echo "💡 使用例:"
	@echo "  EMAIL=user@example.com make setup-all    # Eメール指定で全設定"
	@echo "  make setup-git                           # 実行時にEメール入力"
	@echo ""
	@echo "🆕 Ubuntu 25.04 (Plucky Puffin) 対応:"
	@echo "  新しいパッケージ名に対応しています（libfuse2t64など）"
	@echo "  一部のPPAが利用できない場合があります"
